/* Generated by AN DISI Unibo */ 
package it.unibo.referee

import it.unibo.kactor.*
import alice.tuprolog.*
import unibo.basicomm23.*
import unibo.basicomm23.interfaces.*
import unibo.basicomm23.utils.*
import kotlinx.coroutines.CoroutineScope
import kotlinx.coroutines.delay
import kotlinx.coroutines.launch
import kotlinx.coroutines.runBlocking
import it.unibo.kactor.sysUtil.createActor   //Sept2023

//User imports JAN2024

class Referee ( name: String, scope: CoroutineScope, isconfined: Boolean=false  ) : ActorBasicFsm( name, scope, confined=isconfined ){

	override fun getInitialState() : String{
		return "s0"
	}
	override fun getBody() : (ActorBasicFsm.() -> Unit){
		//val interruptedStateTransitions = mutableListOf<Transition>()
		 var J = 0; var NLAST = 0; val TOBSMAX=3000L  
		return { //this:ActionBasciFsm
				state("s0") { //this:State
					action { //it:State
						CommUtils.outmagenta("$name STARTS")
						observeResource("localhost","8080","ctxtest","ping","ballview")
						observeResource("localhost","8080","ctxtest","pong","ballview")
						delay(2000) 
						CommUtils.outblue("Invio messaggio iniziale")
						forward("ball", "ball(0)" ,"ping" ) 
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
				 	 		stateTimer = TimerActor("timer_s0", 
				 	 					  scope, context!!, "local_tout_"+name+"_s0", TOBSMAX )  //OCT2023
					}	 	 
					 transition(edgeName="t06",targetState="gameended",cond=whenTimeout("local_tout_"+name+"_s0"))   
					transition(edgeName="t07",targetState="updateinfoongame",cond=whenDispatch("ballview"))
				}	 
				state("updateinfoongame") { //this:State
					action { //it:State
						if( checkMsgContent( Term.createTerm("ball(N)"), Term.createTerm("ball(X)"), 
						                        currentMsg.msgContent()) ) { //set msgArgList
								 J = payloadArg(0).toInt()  
								if(  J > 0  
								 ){ NLAST=J  
								}
						}
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
				 	 		stateTimer = TimerActor("timer_updateinfoongame", 
				 	 					  scope, context!!, "local_tout_"+name+"_updateinfoongame", TOBSMAX )  //OCT2023
					}	 	 
					 transition(edgeName="t08",targetState="gameended",cond=whenTimeout("local_tout_"+name+"_updateinfoongame"))   
					transition(edgeName="t09",targetState="updateinfoongame",cond=whenDispatch("ballview"))
				}	 
				state("gameended") { //this:State
					action { //it:State
						if(  NLAST % 2 == 0  
						 ){CommUtils.outblue("vince pong")
						}
						else
						 {CommUtils.outblue("vince ping")
						 }
						CommUtils.outblue("$name waits for request")
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
				 	 		stateTimer = TimerActor("timer_gameended", 
				 	 					  scope, context!!, "local_tout_"+name+"_gameended", 2000.toLong() )  //OCT2023
					}	 	 
					 transition(edgeName="t010",targetState="endsystem",cond=whenTimeout("local_tout_"+name+"_gameended"))   
					transition(edgeName="t011",targetState="handleinfo",cond=whenRequest("info"))
				}	 
				state("handleinfo") { //this:State
					action { //it:State
						answer("info", "obsinfo", "obsinfo($NLAST)"   )  
						 System.exit(0)  
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
				}	 
				state("endsystem") { //this:State
					action { //it:State
						CommUtils.outblue("$name ENDS")
						 System.exit(0)  
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
				}	 
			}
		}
} 
