/* Generated by AN DISI Unibo */ 
package it.unibo.nor_r

import it.unibo.kactor.*
import alice.tuprolog.*
import unibo.basicomm23.*
import unibo.basicomm23.interfaces.*
import unibo.basicomm23.utils.*
import kotlinx.coroutines.CoroutineScope
import kotlinx.coroutines.delay
import kotlinx.coroutines.launch
import kotlinx.coroutines.runBlocking
import it.unibo.kactor.sysUtil.createActor   //Sept2023

//User imports JAN2024

class Nor_r ( name: String, scope: CoroutineScope, isconfined: Boolean=false  ) : ActorBasicFsm( name, scope, confined=isconfined ){

	override fun getInitialState() : String{
		return "s0"
	}
	override fun getBody() : (ActorBasicFsm.() -> Unit){
		//val interruptedStateTransitions = mutableListOf<Transition>()
		 
				var input: Int = 0 
				var back: Int = 1
		return { //this:ActionBasciFsm
				state("s0") { //this:State
					action { //it:State
						CommUtils.outgreen("-----------------------------------------------------------------")
						CommUtils.outgreen("$name START")
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition( edgeName="goto",targetState="out", cond=doswitch() )
				}	 
				state("out") { //this:State
					action { //it:State
						if(  input+back <= 0  
						 ){CommUtils.outgreen("$name: 1")
						forward("out", "out(1)" ,"nor_s" ) 
						}
						else
						 {CommUtils.outgreen("$name: 0")
						 forward("out", "out(0)" ,"nor_s" ) 
						 }
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition(edgeName="t02",targetState="handle_back",cond=whenDispatch("out"))
					transition(edgeName="t03",targetState="handle_in",cond=whenDispatch("in"))
				}	 
				state("handle_back") { //this:State
					action { //it:State
						if( checkMsgContent( Term.createTerm("out(X)"), Term.createTerm("out(X)"), 
						                        currentMsg.msgContent()) ) { //set msgArgList
								 back = payloadArg(0).toInt()  
						}
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition( edgeName="goto",targetState="out", cond=doswitch() )
				}	 
				state("handle_in") { //this:State
					action { //it:State
						if( checkMsgContent( Term.createTerm("in(X)"), Term.createTerm("in(X)"), 
						                        currentMsg.msgContent()) ) { //set msgArgList
								 input = payloadArg(0).toInt()  
						}
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition( edgeName="goto",targetState="out", cond=doswitch() )
				}	 
			}
		}
} 
