/* Generated by AN DISI Unibo */ 
package it.unibo.ping

import it.unibo.kactor.*
import alice.tuprolog.*
import unibo.basicomm23.*
import unibo.basicomm23.interfaces.*
import unibo.basicomm23.utils.*
import kotlinx.coroutines.CoroutineScope
import kotlinx.coroutines.delay
import kotlinx.coroutines.launch
import kotlinx.coroutines.runBlocking
import it.unibo.kactor.sysUtil.createActor   //Sept2023

//User imports JAN2024

class Ping ( name: String, scope: CoroutineScope, isconfined: Boolean=false  ) : ActorBasicFsm( name, scope, confined=isconfined ){

	override fun getInitialState() : String{
		return "s0"
	}
	override fun getBody() : (ActorBasicFsm.() -> Unit){
		//val interruptedStateTransitions = mutableListOf<Transition>()
		return { //this:ActionBasciFsm
				state("s0") { //this:State
					action { //it:State
						CommUtils.outblue("Ping START")
						delay(1000) 
						CommUtils.outblue("Ping")
						request("hit", "hit(a)" ,"pong" )  
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition(edgeName="t00",targetState="handleHit",cond=whenReply("hit_resp"))
					transition(edgeName="t01",targetState="handleMiss",cond=whenReply("miss_resp"))
				}	 
				state("handleHit") { //this:State
					action { //it:State
						if( checkMsgContent( Term.createTerm("hit(N)"), Term.createTerm("hit(A)"), 
						                        currentMsg.msgContent()) ) { //set msgArgList
								delay(1000) 
								if(  Math.random()*100+1 <= 90  
								 ){CommUtils.outblue("Ping")
								request("hit", "hit(a)" ,"pong" )  
								}
								else
								 {CommUtils.outblue("YOU LOSE")
								 forward("miss", "miss(a)" ,"pong" ) 
								  System.exit(0)  
								 }
						}
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition(edgeName="t02",targetState="handleHit",cond=whenReply("hit_resp"))
					transition(edgeName="t03",targetState="handleMiss",cond=whenReply("miss_resp"))
				}	 
				state("handleMiss") { //this:State
					action { //it:State
						if( checkMsgContent( Term.createTerm("miss(N)"), Term.createTerm("miss(A)"), 
						                        currentMsg.msgContent()) ) { //set msgArgList
								CommUtils.outblue("YOU WIN")
								 System.exit(0)  
						}
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
				}	 
			}
		}
} 
